"""Pure-Python public value objects for the CAM domain."""

from hms_cadcam.cam.domain.errors import (
    CamError,
    CamUnitError,
    CamValidationError,
    GeometryReferenceError,
    UnsupportedCamSchemaError,
)
from hms_cadcam.cam.domain.geometry_reference import (
    HMS_GEOMETRY_REFERENCE_SCHEME,
    HMS_GEOMETRY_REFERENCE_SCHEME_VERSION,
    GeometryReference,
    GeometryReferenceKind,
    GeometryReferenceResolver,
    GeometryRepresentationKind,
    GeometryResolutionEvidence,
    GeometryResolutionResult,
    GeometryResolutionStatus,
    assess_geometry_resolution,
)
from hms_cadcam.cam.domain.ids import (
    CAM_ID_TYPES,
    CamJobId,
    CamNodeId,
    GeometryReferenceId,
    HolderDefinitionId,
    MachineDefinitionId,
    OperationId,
    SetupId,
    ToolAssemblyId,
    ToolDefinitionId,
    ToolpathArtifactId,
)
from hms_cadcam.cam.domain.revision import (
    ContentFingerprint,
    DependencyFingerprint,
    GeometryFingerprint,
    Revision,
)
from hms_cadcam.cam.domain.units import (
    Angle,
    AngleUnit,
    FeedRate,
    FeedUnit,
    Length,
    LengthUnit,
    SpindleSpeed,
    SpindleSpeedUnit,
)

__all__ = [
    "CAM_ID_TYPES",
    "Angle",
    "AngleUnit",
    "CamError",
    "CamJobId",
    "CamNodeId",
    "CamUnitError",
    "CamValidationError",
    "ContentFingerprint",
    "DependencyFingerprint",
    "FeedRate",
    "FeedUnit",
    "GeometryFingerprint",
    "GeometryReference",
    "GeometryReferenceError",
    "GeometryReferenceId",
    "GeometryReferenceKind",
    "GeometryReferenceResolver",
    "GeometryRepresentationKind",
    "GeometryResolutionEvidence",
    "GeometryResolutionResult",
    "GeometryResolutionStatus",
    "HolderDefinitionId",
    "HMS_GEOMETRY_REFERENCE_SCHEME",
    "HMS_GEOMETRY_REFERENCE_SCHEME_VERSION",
    "Length",
    "LengthUnit",
    "MachineDefinitionId",
    "OperationId",
    "Revision",
    "SetupId",
    "SpindleSpeed",
    "SpindleSpeedUnit",
    "ToolAssemblyId",
    "ToolDefinitionId",
    "ToolpathArtifactId",
    "UnsupportedCamSchemaError",
    "assess_geometry_resolution",
]
