"""Public Stage 8A.3.1 Z-Level Finishing foundation API."""

from .geometry import (
    build_machining_frame,
    calculate_region_bounds,
    plan_level_schedule,
    trace_z_level,
)
from .models import (
    Z_LEVEL_FINISHING_ALGORITHM_VERSION,
    Z_LEVEL_FINISHING_STRATEGY_KEY,
    Z_LEVEL_FINISHING_STRATEGY_VERSION,
    ContactResolver,
    ProgressCallback,
    ZLevelBoundaryClassification,
    ZLevelBoundaryPolicy,
    ZLevelArtifactLifecycle,
    ZLevelArtifactStatus,
    ZLevelContour,
    ZLevelFinishingError,
    ZLevelFinishingParameters,
    ZLevelLoopType,
    ZLevelLinkingMode,
    ZLevelMachiningFrame,
    ZLevelOrientation,
    ZLevelPass,
    ZLevelPathPoint,
    ZLevelPreview,
    ZLevelProgress,
    ZLevelProgressPhase,
    ZLevelRegionBounds,
    ZLevelResolvedContact,
    ZLevelSchedule,
    ZLevelSegment,
    ZLevelStatistics,
)
from .service import (
    ZLevelFinishingCandidate,
    ZLevelFinishingComputeResult,
    ZLevelFinishingGenerator,
    ZLevelFinishingInputs,
    calculate_and_publish_z_level_finishing,
    z_level_artifact_has_safe_contract,
)
from hms_cadcam.cam.cam3d.parallel.safety_models import (
    ParallelGeometrySource as ZLevelGeometrySource,
    ParallelSafetyDiagnostic as ZLevelSafetyDiagnostic,
    ParallelSafetyMotion as ZLevelSafetyMotion,
    ParallelSafetyPolicy as ZLevelSafetyPolicy,
    ParallelSafetyReport as ZLevelSafetyReport,
    ParallelSafetyStatistics as ZLevelSafetyStatistics,
    ParallelSafetyStatus as ZLevelSafetyStatus,
    ParallelToolComponent as ZLevelToolComponent,
)

__all__ = [
    "Z_LEVEL_FINISHING_ALGORITHM_VERSION",
    "Z_LEVEL_FINISHING_STRATEGY_KEY",
    "Z_LEVEL_FINISHING_STRATEGY_VERSION",
    "ContactResolver",
    "ProgressCallback",
    "ZLevelBoundaryClassification",
    "ZLevelBoundaryPolicy",
    "ZLevelArtifactLifecycle",
    "ZLevelArtifactStatus",
    "ZLevelContour",
    "ZLevelFinishingCandidate",
    "ZLevelFinishingComputeResult",
    "ZLevelFinishingError",
    "ZLevelFinishingGenerator",
    "ZLevelFinishingInputs",
    "ZLevelFinishingParameters",
    "ZLevelLinkingMode",
    "ZLevelLoopType",
    "ZLevelMachiningFrame",
    "ZLevelOrientation",
    "ZLevelPass",
    "ZLevelPathPoint",
    "ZLevelPreview",
    "ZLevelProgress",
    "ZLevelProgressPhase",
    "ZLevelRegionBounds",
    "ZLevelResolvedContact",
    "ZLevelGeometrySource",
    "ZLevelSafetyDiagnostic",
    "ZLevelSafetyMotion",
    "ZLevelSafetyPolicy",
    "ZLevelSafetyReport",
    "ZLevelSafetyStatistics",
    "ZLevelSafetyStatus",
    "ZLevelToolComponent",
    "ZLevelSchedule",
    "ZLevelSegment",
    "ZLevelStatistics",
    "build_machining_frame",
    "calculate_and_publish_z_level_finishing",
    "calculate_region_bounds",
    "plan_level_schedule",
    "trace_z_level",
    "z_level_artifact_has_safe_contract",
]
