"""Public Parallel Finishing Foundation API (Stage 8A.2.1)."""

from .models import (
    PARALLEL_FINISHING_ALGORITHM_VERSION,
    PARALLEL_FINISHING_STRATEGY_KEY,
    PARALLEL_FINISHING_STRATEGY_VERSION,
    ContactResolver,
    ParallelCutDirection,
    ParallelFinishingError,
    ParallelFinishingParameters,
    ParallelLinkingMode,
    ParallelNormalSource,
    ParallelMachiningFrame,
    ParallelPass,
    ParallelPathPoint,
    ParallelPreview,
    ParallelProgress,
    ParallelProgressPhase,
    ParallelResolvedContact,
    ParallelRegionBounds,
    ParallelSegment,
    ParallelStatistics,
    ProgressCallback,
)
from .geometry import (
    ParallelIntersectionOutput,
    build_frame_axes,
    build_machining_frame,
    calculate_region_bounds,
    intersect_parallel_passes,
    plan_pass_positions,
)
from .service import (
    ParallelFinishingCandidate,
    ParallelFinishingComputeResult,
    ParallelFinishingGenerator,
    ParallelFinishingInputs,
    calculate_and_publish_parallel_finishing,
)

__all__ = [
    "PARALLEL_FINISHING_ALGORITHM_VERSION",
    "PARALLEL_FINISHING_STRATEGY_KEY",
    "PARALLEL_FINISHING_STRATEGY_VERSION",
    "ContactResolver",
    "ParallelCutDirection",
    "ParallelFinishingError",
    "ParallelFinishingCandidate",
    "ParallelFinishingComputeResult",
    "ParallelFinishingGenerator",
    "ParallelFinishingInputs",
    "ParallelFinishingParameters",
    "ParallelLinkingMode",
    "ParallelNormalSource",
    "ParallelMachiningFrame",
    "ParallelPass",
    "ParallelPathPoint",
    "ParallelPreview",
    "ParallelProgress",
    "ParallelProgressPhase",
    "ParallelResolvedContact",
    "ParallelRegionBounds",
    "ParallelSegment",
    "ParallelStatistics",
    "ParallelIntersectionOutput",
    "ProgressCallback",
    "build_frame_axes",
    "build_machining_frame",
    "calculate_and_publish_parallel_finishing",
    "calculate_region_bounds",
    "intersect_parallel_passes",
    "plan_pass_positions",
]
