"""Public CAD kernel abstractions for HMS CAD/CAM."""

from hms_cadcam.cad.factory import CadKernelFactory
from hms_cadcam.cad.kernel import CadKernel
from hms_cadcam.cad.models import (
    BoundingBox,
    CadDocumentId,
    CadDocumentKind,
    CadDocumentMetadata,
    CadFormat,
    CadGeometryKind,
    CadImportResult,
    CadKernelStatus,
    CadUnits,
    MeshStatistics,
    TopologyCounts,
    XcafAssemblyMetadata,
    XcafColor,
    XcafNameSource,
    XcafNodeRole,
    XcafOccurrenceId,
    XcafOccurrenceMetadata,
    XcafProductId,
    XcafProductMetadata,
    XcafSourceAppearance,
    XcafSubshapeAppearance,
    XcafTransform,
)
from hms_cadcam.cad.persistent_keys import (
    PersistentCadObjectKey,
    TopologyPath,
    TopologyPathVersion,
)

__all__ = [
    "BoundingBox",
    "CadDocumentId",
    "CadDocumentKind",
    "CadDocumentMetadata",
    "CadFormat",
    "CadGeometryKind",
    "CadImportResult",
    "CadKernel",
    "CadKernelFactory",
    "CadKernelStatus",
    "CadUnits",
    "MeshStatistics",
    "PersistentCadObjectKey",
    "TopologyPath",
    "TopologyPathVersion",
    "TopologyCounts",
    "XcafAssemblyMetadata",
    "XcafColor",
    "XcafNameSource",
    "XcafNodeRole",
    "XcafOccurrenceId",
    "XcafOccurrenceMetadata",
    "XcafProductId",
    "XcafProductMetadata",
    "XcafSourceAppearance",
    "XcafSubshapeAppearance",
    "XcafTransform",
]
