"""Production Function Editor strategies migrated after Stage 9A.4."""

from hms_cadcam.ui.function_editor.strategies.contour import (
    ContourEditorContext,
    ContourEditorDraftContext,
    ContourOperationUpdate,
    build_contour_schema,
    contour_applied_values,
    prepare_contour_update,
    validate_contour_schema_contract,
)
from hms_cadcam.ui.function_editor.strategies.common_milling import (
    FacingEditorContext,
    FacingEditorDraftContext,
    FacingEditorVariant,
    FacingOperationUpdate,
    facing_applied_values,
    facing_draft_transform,
    prepare_facing_update,
    validate_facing_schema_contract,
)
from hms_cadcam.ui.function_editor.strategies.facing import build_facing_schema
from hms_cadcam.ui.function_editor.strategies.planar_face_facing import (
    build_planar_face_facing_schema,
)
from hms_cadcam.ui.function_editor.strategies.pocket import (
    PocketEditorContext,
    PocketEditorDraftContext,
    PocketOperationUpdate,
    build_pocket_schema,
    pocket_applied_values,
    prepare_pocket_update,
    validate_pocket_schema_contract,
)
from hms_cadcam.ui.function_editor.strategies.common_drilling import (
    DrillingFamilyEditorContext,
    DrillingFamilyEditorDraftContext,
    DrillingFamilyEditorKind,
    DrillingFamilyOperationUpdate,
    drilling_family_applied_values,
    drilling_family_geometry_values,
    prepare_drilling_family_update,
    strategy_from_operation,
    validate_drilling_family_schema_contract,
)
from hms_cadcam.ui.function_editor.strategies.drilling import build_drilling_schema
from hms_cadcam.ui.function_editor.strategies.tapping import build_tapping_schema
from hms_cadcam.ui.function_editor.strategies.reaming import build_reaming_schema
from hms_cadcam.ui.function_editor.strategies.boring import build_boring_schema
from hms_cadcam.ui.function_editor.strategies.parallel import (
    PARALLEL_EDITOR_ID,
    PARALLEL_EDITOR_STRATEGY_KEY,
    ParallelEditorContext,
    ParallelEditorDraftContext,
    ParallelOperationUpdate,
    ParallelSafetyPresentation,
    build_parallel_schema,
    parallel_applied_values,
    parallel_draft_derived_values,
    parallel_safety_presentation,
    parallel_validation_diagnostics,
    prepare_parallel_update,
    validate_parallel_schema_contract,
)
from hms_cadcam.ui.function_editor.strategies.zlevel import (
    Z_LEVEL_EDITOR_ID,
    Z_LEVEL_EDITOR_STRATEGY_KEY,
    ZLevelEditorContext,
    ZLevelEditorDraftContext,
    ZLevelOperationUpdate,
    ZLevelSafetyPresentation,
    build_z_level_schema,
    prepare_z_level_update,
    validate_z_level_schema_contract,
    z_level_applied_values,
    z_level_draft_derived_values,
    z_level_safety_presentation,
    z_level_validation_diagnostics,
)

__all__ = [
    "ContourEditorContext",
    "ContourEditorDraftContext",
    "ContourOperationUpdate",
    "FacingEditorContext",
    "FacingEditorDraftContext",
    "FacingEditorVariant",
    "FacingOperationUpdate",
    "PocketEditorContext",
    "PocketEditorDraftContext",
    "PocketOperationUpdate",
    "PARALLEL_EDITOR_ID",
    "PARALLEL_EDITOR_STRATEGY_KEY",
    "ParallelEditorContext",
    "ParallelEditorDraftContext",
    "ParallelOperationUpdate",
    "ParallelSafetyPresentation",
    "Z_LEVEL_EDITOR_ID",
    "Z_LEVEL_EDITOR_STRATEGY_KEY",
    "ZLevelEditorContext",
    "ZLevelEditorDraftContext",
    "ZLevelOperationUpdate",
    "ZLevelSafetyPresentation",
    "DrillingFamilyEditorContext",
    "DrillingFamilyEditorDraftContext",
    "DrillingFamilyEditorKind",
    "DrillingFamilyOperationUpdate",
    "build_boring_schema",
    "build_contour_schema",
    "build_drilling_schema",
    "build_facing_schema",
    "build_planar_face_facing_schema",
    "build_pocket_schema",
    "build_parallel_schema",
    "build_z_level_schema",
    "build_reaming_schema",
    "build_tapping_schema",
    "contour_applied_values",
    "drilling_family_applied_values",
    "drilling_family_geometry_values",
    "facing_applied_values",
    "facing_draft_transform",
    "pocket_applied_values",
    "parallel_applied_values",
    "parallel_draft_derived_values",
    "parallel_safety_presentation",
    "parallel_validation_diagnostics",
    "prepare_contour_update",
    "prepare_drilling_family_update",
    "prepare_facing_update",
    "prepare_pocket_update",
    "prepare_parallel_update",
    "prepare_z_level_update",
    "strategy_from_operation",
    "validate_contour_schema_contract",
    "validate_drilling_family_schema_contract",
    "validate_facing_schema_contract",
    "validate_pocket_schema_contract",
    "validate_parallel_schema_contract",
    "validate_z_level_schema_contract",
    "z_level_applied_values",
    "z_level_draft_derived_values",
    "z_level_safety_presentation",
    "z_level_validation_diagnostics",
]
