"""Constants for the versioned HMS project format."""

PROJECT_FORMAT = "HMS_PROJECT"
PROJECT_FORMAT_VERSION = 1
DATABASE_SCHEMA_VERSION = 1
MANIFEST_FILENAME = "project.hms.json"
DATABASE_FILENAME = "project.db"
PROJECT_SUFFIX = ".HMS"
SOURCE_DIRECTORY = "source"
APPLICATION_NAME = "HMS CAD/CAM"
APPLICATION_VERSION = "0.1.0"
RECENT_PROJECTS_FORMAT = "HMS_RECENT_PROJECTS"
RECENT_PROJECTS_VERSION = 1
MAX_RECENT_PROJECTS = 10
SESSION_LOCK_FILENAME = "session.lock"
SESSION_LOCK_FORMAT = "HMS_SESSION_LOCK"
SESSION_LOCK_FORMAT_VERSION = 1
OWNED_DIRECTORY_METADATA_FILENAME = ".hms-owner.json"
OWNED_DIRECTORY_FORMAT = "HMS_OWNED_DIRECTORY"
OWNED_DIRECTORY_FORMAT_VERSION = 1
AUTOSAVE_DIRECTORY = "autosave"
BACKUPS_DIRECTORY = "backups"
TEMP_DIRECTORY = "temp"
